In [110]:
import os
import pandas as pd

In [111]:
all_data = pd.read_csv("wheel_rpm.csv")
all_data.head()

                         time  .data
0  2024/02/13/18:24:41.833323    0.0
1  2024/02/13/18:24:42.171947    0.0
2  2024/02/13/18:24:42.509258    0.0
3  2024/02/13/18:24:42.847682    0.0
4  2024/02/13/18:24:43.185034    0.0

In [112]:
def get_timem(address):
    address.split("/")[3].strip(" ")
    return address.replace(":", ".")
def get_timeM(address):
    return address.split(".")[1] + address.split(".")[2]
all_data['time_m'] = all_data['time'].apply(lambda x: f"{get_timem(x)}")
all_data['time_M'] = all_data['time_m'].apply(lambda x: f"{get_timeM(x)}")
all_data.head()

                         time  .data                      time_m time_M
0  2024/02/13/18:24:41.833323    0.0  2024/02/13/18.24.41.833323   2441
1  2024/02/13/18:24:42.171947    0.0  2024/02/13/18.24.42.171947   2442
2  2024/02/13/18:24:42.509258    0.0  2024/02/13/18.24.42.509258   2442
3  2024/02/13/18:24:42.847682    0.0  2024/02/13/18.24.42.847682   2442
4  2024/02/13/18:24:43.185034    0.0  2024/02/13/18.24.43.185034   2443

In [113]:
all_data = all_data.drop('time', axis = 1)
all_data = all_data.drop('time_m', axis = 1)
all_data.head()

   .data time_M
0    0.0   2441
1    0.0   2442
2    0.0   2442
3    0.0   2442
4    0.0   2443

In [114]:
size = list(all_data['time_M'])
dataa = list(all_data['.data'])
print(len(size))
print(size[920])
print(dataa[920])
print(size)

922
2952
0.0
['2441', '2442', '2442', '2442', '2443', '2443', '2443', '2444', '2444', '2444', '2445', '2445', '2445', '2446', '2446', '2446', '2447', '2447', '2447', '2448', '2448', '2448', '2449', '2449', '2449', '2450', '2450', '2450', '2451', '2451', '2451', '2452', '2452', '2452', '2453', '2453', '2453', '2454', '2454', '2454', '2455', '2455', '2456', '2456', '2456', '2457', '2457', '2457', '2458', '2458', '2458', '2459', '2459', '2459', '2500', '2500', '2500', '2501', '2501', '2501', '2502', '2502', '2502', '2503', '2503', '2503', '2504', '2504', '2504', '2505', '2505', '2505', '2506', '2506', '2506', '2507', '2507', '2507', '2508', '2508', '2508', '2509', '2509', '2509', '2510', '2510', '2510', '2511', '2511', '2511', '2512', '2512', '2512', '2513', '2513', '2513', '2514', '2514', '2514', '2515', '2515', '2515', '2516', '2516', '2516', '2517', '2517', '2517', '2518', '2518', '2518', '2519', '2519', '2519', '2520', '2520', '2520', '2521', '2521', '2521', '2522', '2522', '2522', '2523', '2523', '2524', '2524', '2524', '2525', '2525', '2525', '2526', '2526', '2526', '2527', '2527', '2527', '2528', '2528', '2528', '2529', '2529', '2529', '2530', '2530', '2530', '2531', '2531', '2531', '2532', '2532', '2532', '2533', '2533', '2533', '2534', '2534', '2534', '2535', '2535', '2535', '2536', '2536', '2536', '2537', '2537', '2537', '2538', '2538', '2538', '2539', '2539', '2539', '2540', '2540', '2540', '2541', '2541', '2541', '2542', '2542', '2542', '2543', '2543', '2543', '2544', '2544', '2544', '2545', '2545', '2545', '2546', '2546', '2546', '2547', '2547', '2547', '2548', '2548', '2548', '2549', '2549', '2549', '2550', '2550', '2551', '2551', '2551', '2552', '2552', '2552', '2553', '2553', '2553', '2554', '2554', '2554', '2555', '2555', '2555', '2556', '2556', '2556', '2557', '2557', '2557', '2558', '2558', '2558', '2559', '2559', '2559', '2600', '2600', '2600', '2601', '2601', '2601', '2602', '2602', '2602', '2603', '2603', '2603', '2604', '2604', '2604', '2605', '2605', '2605', '2606', '2606', '2606', '2607', '2607', '2607', '2608', '2608', '2608', '2609', '2609', '2609', '2610', '2610', '2610', '2611', '2611', '2611', '2612', '2612', '2612', '2613', '2613', '2613', '2614', '2614', '2614', '2615', '2615', '2615', '2616', '2616', '2616', '2617', '2617', '2617', '2618', '2618', '2619', '2619', '2619', '2620', '2620', '2620', '2621', '2621', '2621', '2622', '2622', '2622', '2623', '2623', '2623', '2624', '2624', '2624', '2625', '2625', '2625', '2626', '2626', '2626', '2627', '2627', '2627', '2628', '2628', '2628', '2629', '2629', '2629', '2630', '2630', '2630', '2631', '2631', '2631', '2632', '2632', '2632', '2633', '2633', '2633', '2634', '2634', '2634', '2635', '2635', '2635', '2636', '2636', '2636', '2637', '2637', '2637', '2638', '2638', '2638', '2639', '2639', '2639', '2640', '2640', '2640', '2641', '2641', '2641', '2642', '2642', '2642', '2643', '2643', '2643', '2644', '2644', '2644', '2645', '2645', '2646', '2646', '2646', '2647', '2647', '2647', '2648', '2648', '2648', '2649', '2649', '2649', '2650', '2650', '2650', '2651', '2651', '2651', '2652', '2652', '2652', '2653', '2653', '2653', '2654', '2654', '2654', '2655', '2655', '2655', '2656', '2656', '2656', '2657', '2657', '2657', '2658', '2658', '2658', '2659', '2659', '2659', '2700', '2700', '2700', '2701', '2701', '2701', '2702', '2702', '2702', '2703', '2703', '2703', '2704', '2704', '2704', '2705', '2705', '2705', '2706', '2706', '2706', '2707', '2707', '2707', '2708', '2708', '2708', '2709', '2709', '2709', '2710', '2710', '2710', '2711', '2711', '2711', '2712', '2712', '2712', '2713', '2713', '2714', '2714', '2714', '2715', '2715', '2715', '2716', '2716', '2716', '2717', '2717', '2717', '2718', '2718', '2718', '2719', '2719', '2719', '2720', '2720', '2720', '2721', '2721', '2721', '2722', '2722', '2722', '2723', '2723', '2723', '2724', '2724', '2724', '2725', '2725', '2725', '2726', '2726', '2726', '2727', '2727', '2727', '2728', '2728', '2728', '2729', '2729', '2729', '2730', '2730', '2730', '2731', '2731', '2731', '2732', '2732', '2732', '2733', '2733', '2733', '2734', '2734', '2734', '2735', '2735', '2735', '2736', '2736', '2736', '2737', '2737', '2737', '2738', '2738', '2738', '2739', '2739', '2739', '2740', '2740', '2741', '2741', '2741', '2742', '2742', '2742', '2743', '2743', '2743', '2744', '2744', '2744', '2745', '2745', '2745', '2746', '2746', '2746', '2747', '2747', '2747', '2748', '2748', '2748', '2749', '2749', '2749', '2750', '2750', '2750', '2751', '2751', '2751', '2752', '2752', '2752', '2753', '2753', '2753', '2754', '2754', '2754', '2755', '2755', '2755', '2756', '2756', '2756', '2757', '2757', '2757', '2758', '2758', '2758', '2759', '2759', '2759', '2800', '2800', '2800', '2801', '2801', '2801', '2802', '2802', '2802', '2803', '2803', '2803', '2804', '2804', '2804', '2805', '2805', '2805', '2806', '2806', '2806', '2807', '2807', '2807', '2808', '2808', '2809', '2809', '2809', '2810', '2810', '2810', '2811', '2811', '2811', '2812', '2812', '2812', '2813', '2813', '2813', '2814', '2814', '2814', '2815', '2815', '2815', '2816', '2816', '2816', '2817', '2817', '2817', '2818', '2818', '2818', '2819', '2819', '2819', '2820', '2820', '2820', '2821', '2821', '2821', '2822', '2822', '2822', '2823', '2823', '2823', '2824', '2824', '2824', '2825', '2825', '2825', '2826', '2826', '2826', '2827', '2827', '2827', '2828', '2828', '2828', '2829', '2829', '2829', '2830', '2830', '2830', '2831', '2831', '2831', '2832', '2832', '2832', '2833', '2833', '2833', '2834', '2834', '2834', '2835', '2835', '2835', '2836', '2836', '2837', '2837', '2837', '2838', '2838', '2838', '2839', '2839', '2839', '2840', '2840', '2840', '2841', '2841', '2841', '2842', '2842', '2842', '2843', '2843', '2843', '2844', '2844', '2844', '2845', '2845', '2845', '2846', '2846', '2846', '2847', '2847', '2847', '2848', '2848', '2848', '2849', '2849', '2849', '2850', '2850', '2850', '2851', '2851', '2851', '2852', '2852', '2852', '2853', '2853', '2853', '2854', '2854', '2854', '2855', '2855', '2855', '2856', '2856', '2856', '2857', '2857', '2857', '2858', '2858', '2858', '2859', '2859', '2859', '2900', '2900', '2900', '2901', '2901', '2901', '2902', '2902', '2902', '2903', '2903', '2904', '2904', '2904', '2905', '2905', '2905', '2906', '2906', '2906', '2907', '2907', '2907', '2908', '2908', '2908', '2909', '2909', '2909', '2910', '2910', '2910', '2911', '2911', '2911', '2912', '2912', '2912', '2913', '2913', '2913', '2914', '2914', '2914', '2915', '2915', '2915', '2916', '2916', '2916', '2917', '2917', '2917', '2918', '2918', '2918', '2919', '2919', '2919', '2920', '2920', '2920', '2921', '2921', '2921', '2922', '2922', '2922', '2923', '2923', '2923', '2924', '2924', '2924', '2925', '2925', '2925', '2926', '2926', '2926', '2927', '2927', '2927', '2928', '2928', '2928', '2929', '2929', '2929', '2930', '2930', '2930', '2931', '2931', '2932', '2932', '2932', '2933', '2933', '2933', '2934', '2934', '2934', '2935', '2935', '2935', '2936', '2936', '2936', '2937', '2937', '2937', '2938', '2938', '2938', '2939', '2939', '2939', '2940', '2940', '2940', '2941', '2941', '2941', '2942', '2942', '2942', '2943', '2943', '2943', '2944', '2944', '2944', '2945', '2945', '2945', '2946', '2946', '2946', '2947', '2947', '2947', '2948', '2948', '2948', '2949', '2949', '2949', '2950', '2950', '2950', '2951', '2951', '2951', '2952', '2952']

In [115]:
for a, i in enumerate(size):
    size[a] = int(size[a])
    dataa[a] = int(dataa[a])
print(size)
print(dataa)

[2441, 2442, 2442, 2442, 2443, 2443, 2443, 2444, 2444, 2444, 2445, 2445, 2445, 2446, 2446, 2446, 2447, 2447, 2447, 2448, 2448, 2448, 2449, 2449, 2449, 2450, 2450, 2450, 2451, 2451, 2451, 2452, 2452, 2452, 2453, 2453, 2453, 2454, 2454, 2454, 2455, 2455, 2456, 2456, 2456, 2457, 2457, 2457, 2458, 2458, 2458, 2459, 2459, 2459, 2500, 2500, 2500, 2501, 2501, 2501, 2502, 2502, 2502, 2503, 2503, 2503, 2504, 2504, 2504, 2505, 2505, 2505, 2506, 2506, 2506, 2507, 2507, 2507, 2508, 2508, 2508, 2509, 2509, 2509, 2510, 2510, 2510, 2511, 2511, 2511, 2512, 2512, 2512, 2513, 2513, 2513, 2514, 2514, 2514, 2515, 2515, 2515, 2516, 2516, 2516, 2517, 2517, 2517, 2518, 2518, 2518, 2519, 2519, 2519, 2520, 2520, 2520, 2521, 2521, 2521, 2522, 2522, 2522, 2523, 2523, 2524, 2524, 2524, 2525, 2525, 2525, 2526, 2526, 2526, 2527, 2527, 2527, 2528, 2528, 2528, 2529, 2529, 2529, 2530, 2530, 2530, 2531, 2531, 2531, 2532, 2532, 2532, 2533, 2533, 2533, 2534, 2534, 2534, 2535, 2535, 2535, 2536, 2536, 2536, 2537, 2537, 2537, 2538, 2538, 2538, 2539, 2539, 2539, 2540, 2540, 2540, 2541, 2541, 2541, 2542, 2542, 2542, 2543, 2543, 2543, 2544, 2544, 2544, 2545, 2545, 2545, 2546, 2546, 2546, 2547, 2547, 2547, 2548, 2548, 2548, 2549, 2549, 2549, 2550, 2550, 2551, 2551, 2551, 2552, 2552, 2552, 2553, 2553, 2553, 2554, 2554, 2554, 2555, 2555, 2555, 2556, 2556, 2556, 2557, 2557, 2557, 2558, 2558, 2558, 2559, 2559, 2559, 2600, 2600, 2600, 2601, 2601, 2601, 2602, 2602, 2602, 2603, 2603, 2603, 2604, 2604, 2604, 2605, 2605, 2605, 2606, 2606, 2606, 2607, 2607, 2607, 2608, 2608, 2608, 2609, 2609, 2609, 2610, 2610, 2610, 2611, 2611, 2611, 2612, 2612, 2612, 2613, 2613, 2613, 2614, 2614, 2614, 2615, 2615, 2615, 2616, 2616, 2616, 2617, 2617, 2617, 2618, 2618, 2619, 2619, 2619, 2620, 2620, 2620, 2621, 2621, 2621, 2622, 2622, 2622, 2623, 2623, 2623, 2624, 2624, 2624, 2625, 2625, 2625, 2626, 2626, 2626, 2627, 2627, 2627, 2628, 2628, 2628, 2629, 2629, 2629, 2630, 2630, 2630, 2631, 2631, 2631, 2632, 2632, 2632, 2633, 2633, 2633, 2634, 2634, 2634, 2635, 2635, 2635, 2636, 2636, 2636, 2637, 2637, 2637, 2638, 2638, 2638, 2639, 2639, 2639, 2640, 2640, 2640, 2641, 2641, 2641, 2642, 2642, 2642, 2643, 2643, 2643, 2644, 2644, 2644, 2645, 2645, 2646, 2646, 2646, 2647, 2647, 2647, 2648, 2648, 2648, 2649, 2649, 2649, 2650, 2650, 2650, 2651, 2651, 2651, 2652, 2652, 2652, 2653, 2653, 2653, 2654, 2654, 2654, 2655, 2655, 2655, 2656, 2656, 2656, 2657, 2657, 2657, 2658, 2658, 2658, 2659, 2659, 2659, 2700, 2700, 2700, 2701, 2701, 2701, 2702, 2702, 2702, 2703, 2703, 2703, 2704, 2704, 2704, 2705, 2705, 2705, 2706, 2706, 2706, 2707, 2707, 2707, 2708, 2708, 2708, 2709, 2709, 2709, 2710, 2710, 2710, 2711, 2711, 2711, 2712, 2712, 2712, 2713, 2713, 2714, 2714, 2714, 2715, 2715, 2715, 2716, 2716, 2716, 2717, 2717, 2717, 2718, 2718, 2718, 2719, 2719, 2719, 2720, 2720, 2720, 2721, 2721, 2721, 2722, 2722, 2722, 2723, 2723, 2723, 2724, 2724, 2724, 2725, 2725, 2725, 2726, 2726, 2726, 2727, 2727, 2727, 2728, 2728, 2728, 2729, 2729, 2729, 2730, 2730, 2730, 2731, 2731, 2731, 2732, 2732, 2732, 2733, 2733, 2733, 2734, 2734, 2734, 2735, 2735, 2735, 2736, 2736, 2736, 2737, 2737, 2737, 2738, 2738, 2738, 2739, 2739, 2739, 2740, 2740, 2741, 2741, 2741, 2742, 2742, 2742, 2743, 2743, 2743, 2744, 2744, 2744, 2745, 2745, 2745, 2746, 2746, 2746, 2747, 2747, 2747, 2748, 2748, 2748, 2749, 2749, 2749, 2750, 2750, 2750, 2751, 2751, 2751, 2752, 2752, 2752, 2753, 2753, 2753, 2754, 2754, 2754, 2755, 2755, 2755, 2756, 2756, 2756, 2757, 2757, 2757, 2758, 2758, 2758, 2759, 2759, 2759, 2800, 2800, 2800, 2801, 2801, 2801, 2802, 2802, 2802, 2803, 2803, 2803, 2804, 2804, 2804, 2805, 2805, 2805, 2806, 2806, 2806, 2807, 2807, 2807, 2808, 2808, 2809, 2809, 2809, 2810, 2810, 2810, 2811, 2811, 2811, 2812, 2812, 2812, 2813, 2813, 2813, 2814, 2814, 2814, 2815, 2815, 2815, 2816, 2816, 2816, 2817, 2817, 2817, 2818, 2818, 2818, 2819, 2819, 2819, 2820, 2820, 2820, 2821, 2821, 2821, 2822, 2822, 2822, 2823, 2823, 2823, 2824, 2824, 2824, 2825, 2825, 2825, 2826, 2826, 2826, 2827, 2827, 2827, 2828, 2828, 2828, 2829, 2829, 2829, 2830, 2830, 2830, 2831, 2831, 2831, 2832, 2832, 2832, 2833, 2833, 2833, 2834, 2834, 2834, 2835, 2835, 2835, 2836, 2836, 2837, 2837, 2837, 2838, 2838, 2838, 2839, 2839, 2839, 2840, 2840, 2840, 2841, 2841, 2841, 2842, 2842, 2842, 2843, 2843, 2843, 2844, 2844, 2844, 2845, 2845, 2845, 2846, 2846, 2846, 2847, 2847, 2847, 2848, 2848, 2848, 2849, 2849, 2849, 2850, 2850, 2850, 2851, 2851, 2851, 2852, 2852, 2852, 2853, 2853, 2853, 2854, 2854, 2854, 2855, 2855, 2855, 2856, 2856, 2856, 2857, 2857, 2857, 2858, 2858, 2858, 2859, 2859, 2859, 2900, 2900, 2900, 2901, 2901, 2901, 2902, 2902, 2902, 2903, 2903, 2904, 2904, 2904, 2905, 2905, 2905, 2906, 2906, 2906, 2907, 2907, 2907, 2908, 2908, 2908, 2909, 2909, 2909, 2910, 2910, 2910, 2911, 2911, 2911, 2912, 2912, 2912, 2913, 2913, 2913, 2914, 2914, 2914, 2915, 2915, 2915, 2916, 2916, 2916, 2917, 2917, 2917, 2918, 2918, 2918, 2919, 2919, 2919, 2920, 2920, 2920, 2921, 2921, 2921, 2922, 2922, 2922, 2923, 2923, 2923, 2924, 2924, 2924, 2925, 2925, 2925, 2926, 2926, 2926, 2927, 2927, 2927, 2928, 2928, 2928, 2929, 2929, 2929, 2930, 2930, 2930, 2931, 2931, 2932, 2932, 2932, 2933, 2933, 2933, 2934, 2934, 2934, 2935, 2935, 2935, 2936, 2936, 2936, 2937, 2937, 2937, 2938, 2938, 2938, 2939, 2939, 2939, 2940, 2940, 2940, 2941, 2941, 2941, 2942, 2942, 2942, 2943, 2943, 2943, 2944, 2944, 2944, 2945, 2945, 2945, 2946, 2946, 2946, 2947, 2947, 2947, 2948, 2948, 2948, 2949, 2949, 2949, 2950, 2950, 2950, 2951, 2951, 2951, 2952, 2952]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [116]:
# mc_stan = {}
from collections import defaultdict
# mc_stan = {key: [] for key in range(size[0], size[-1])}
# for i,a in zip(size, dataa):
mc_stan = defaultdict(list)

# Use map to iterate over elements of 'a' and 'b' simultaneously and update the result_dict
for key, value in zip(size, dataa):
    mc_stan[key].append(value)

# Convert the defaultdict to a regular dictionary
ans = dict(mc_stan)   
print(ans)

{2441: [0], 2442: [0, 0, 0], 2443: [0, 0, 0], 2444: [0, 0, 0], 2445: [0, 0, 0], 2446: [0, 0, 0], 2447: [0, 0, 0], 2448: [0, 0, 0], 2449: [0, 0, 0], 2450: [0, 0, 0], 2451: [0, 0, 0], 2452: [0, 0, 0], 2453: [0, 0, 0], 2454: [0, 0, 0], 2455: [0, 0], 2456: [0, 0, 0], 2457: [0, 0, 0], 2458: [0, 0, 0], 2459: [0, 0, 0], 2500: [0, 0, 0], 2501: [0, 0, 0], 2502: [0, 0, 0], 2503: [0, 0, 0], 2504: [0, 0, 0], 2505: [0, 0, 0], 2506: [0, 0, 0], 2507: [0, 0, 0], 2508: [0, 0, 0], 2509: [0, 0, 0], 2510: [0, 0, 0], 2511: [0, 0, 0], 2512: [0, 0, 0], 2513: [0, 0, 0], 2514: [0, 0, 0], 2515: [0, 0, 0], 2516: [0, 0, 0], 2517: [0, 0, 0], 2518: [0, 0, 0], 2519: [0, 0, 0], 2520: [0, 0, 0], 2521: [0, 0, 0], 2522: [0, 0, 0], 2523: [0, 0], 2524: [0, 0, 0], 2525: [0, 0, 0], 2526: [0, 0, 0], 2527: [0, 0, 0], 2528: [0, 0, 0], 2529: [0, 0, 0], 2530: [0, 0, 0], 2531: [0, 0, 0], 2532: [0, 0, 0], 2533: [0, 0, 0], 2534: [0, 0, 0], 2535: [0, 0, 0], 2536: [0, 0, 0], 2537: [0, 0, 0], 2538: [0, 0, 0], 2539: [0, 0, 0], 2540: [0, 0, 0], 2541: [0, 0, 0], 2542: [0, 0, 0], 2543: [0, 0, 0], 2544: [0, 0, 0], 2545: [0, 0, 0], 2546: [0, 0, 0], 2547: [0, 0, 0], 2548: [0, 0, 0], 2549: [0, 0, 0], 2550: [0, 0], 2551: [0, 0, 0], 2552: [0, 0, 0], 2553: [0, 0, 0], 2554: [0, 0, 0], 2555: [0, 0, 0], 2556: [0, 0, 0], 2557: [0, 0, 0], 2558: [0, 0, 0], 2559: [0, 0, 0], 2600: [0, 0, 0], 2601: [0, 0, 0], 2602: [0, 0, 0], 2603: [0, 0, 0], 2604: [0, 0, 0], 2605: [0, 0, 0], 2606: [0, 0, 0], 2607: [0, 0, 0], 2608: [0, 0, 0], 2609: [0, 0, 0], 2610: [0, 0, 0], 2611: [0, 0, 0], 2612: [0, 0, 0], 2613: [0, 0, 0], 2614: [0, 0, 0], 2615: [0, 0, 0], 2616: [0, 0, 0], 2617: [0, 0, 0], 2618: [0, 0], 2619: [0, 0, 0], 2620: [0, 0, 0], 2621: [0, 0, 0], 2622: [0, 0, 0], 2623: [0, 0, 0], 2624: [0, 0, 0], 2625: [0, 0, 0], 2626: [0, 0, 0], 2627: [0, 0, 0], 2628: [0, 0, 0], 2629: [0, 0, 0], 2630: [0, 0, 0], 2631: [0, 0, 0], 2632: [0, 0, 0], 2633: [0, 0, 0], 2634: [0, 0, 0], 2635: [0, 0, 0], 2636: [0, 0, 0], 2637: [0, 0, 0], 2638: [0, 0, 0], 2639: [0, 0, 0], 2640: [0, 0, 0], 2641: [0, 0, 0], 2642: [0, 0, 0], 2643: [0, 0, 0], 2644: [0, 0, 0], 2645: [0, 0], 2646: [0, 0, 0], 2647: [0, 0, 0], 2648: [0, 0, 0], 2649: [0, 0, 0], 2650: [0, 0, 0], 2651: [0, 0, 0], 2652: [0, 0, 0], 2653: [0, 0, 0], 2654: [0, 0, 0], 2655: [0, 0, 0], 2656: [0, 0, 0], 2657: [0, 0, 0], 2658: [0, 0, 0], 2659: [0, 0, 0], 2700: [0, 0, 0], 2701: [0, 0, 0], 2702: [0, 0, 0], 2703: [0, 0, 0], 2704: [0, 0, 0], 2705: [0, 0, 0], 2706: [0, 0, 0], 2707: [0, 0, 0], 2708: [0, 0, 0], 2709: [0, 0, 0], 2710: [0, 0, 0], 2711: [0, 0, 0], 2712: [0, 0, 0], 2713: [0, 0], 2714: [0, 0, 0], 2715: [0, 0, 0], 2716: [0, 0, 0], 2717: [0, 0, 0], 2718: [0, 0, 0], 2719: [0, 0, 0], 2720: [0, 0, 0], 2721: [0, 0, 0], 2722: [0, 0, 0], 2723: [0, 0, 0], 2724: [0, 0, 0], 2725: [0, 0, 0], 2726: [0, 0, 0], 2727: [0, 0, 0], 2728: [0, 0, 0], 2729: [0, 0, 0], 2730: [0, 0, 0], 2731: [0, 0, 0], 2732: [0, 0, 0], 2733: [0, 0, 0], 2734: [0, 0, 0], 2735: [0, 0, 0], 2736: [0, 0, 0], 2737: [0, 0, 0], 2738: [0, 0, 0], 2739: [0, 0, 0], 2740: [0, 0], 2741: [0, 0, 0], 2742: [0, 0, 0], 2743: [0, 0, 0], 2744: [0, 0, 0], 2745: [0, 0, 0], 2746: [0, 0, 0], 2747: [0, 0, 0], 2748: [0, 0, 0], 2749: [0, 0, 0], 2750: [0, 0, 0], 2751: [0, 0, 0], 2752: [0, 0, 0], 2753: [0, 0, 0], 2754: [0, 0, 0], 2755: [0, 0, 0], 2756: [0, 0, 0], 2757: [0, 0, 0], 2758: [0, 0, 0], 2759: [0, 0, 0], 2800: [0, 0, 0], 2801: [0, 0, 0], 2802: [0, 0, 0], 2803: [0, 0, 0], 2804: [0, 0, 0], 2805: [0, 0, 0], 2806: [0, 0, 0], 2807: [0, 0, 0], 2808: [0, 0], 2809: [0, 0, 0], 2810: [0, 0, 0], 2811: [0, 0, 0], 2812: [0, 0, 0], 2813: [0, 0, 0], 2814: [0, 0, 0], 2815: [0, 0, 0], 2816: [0, 0, 0], 2817: [0, 0, 0], 2818: [0, 0, 0], 2819: [0, 0, 0], 2820: [0, 0, 0], 2821: [0, 0, 0], 2822: [0, 0, 0], 2823: [0, 0, 0], 2824: [0, 0, 0], 2825: [0, 0, 0], 2826: [0, 0, 0], 2827: [0, 0, 0], 2828: [0, 0, 0], 2829: [0, 0, 0], 2830: [0, 0, 0], 2831: [0, 0, 0], 2832: [0, 0, 0], 2833: [0, 0, 0], 2834: [0, 0, 0], 2835: [0, 0, 0], 2836: [0, 0], 2837: [0, 0, 0], 2838: [0, 0, 0], 2839: [0, 0, 0], 2840: [0, 0, 0], 2841: [0, 0, 0], 2842: [0, 0, 0], 2843: [0, 0, 0], 2844: [0, 0, 0], 2845: [0, 0, 0], 2846: [0, 0, 0], 2847: [0, 0, 0], 2848: [0, 0, 0], 2849: [0, 0, 0], 2850: [0, 0, 0], 2851: [0, 0, 0], 2852: [0, 0, 0], 2853: [0, 0, 0], 2854: [0, 0, 0], 2855: [0, 0, 0], 2856: [0, 0, 0], 2857: [0, 0, 0], 2858: [0, 0, 0], 2859: [0, 0, 0], 2900: [0, 0, 0], 2901: [0, 0, 0], 2902: [0, 0, 0], 2903: [0, 0], 2904: [0, 0, 0], 2905: [0, 0, 0], 2906: [0, 0, 0], 2907: [0, 0, 0], 2908: [0, 0, 0], 2909: [0, 0, 0], 2910: [0, 0, 0], 2911: [0, 0, 0], 2912: [0, 0, 0], 2913: [0, 0, 0], 2914: [0, 0, 0], 2915: [0, 0, 0], 2916: [0, 0, 0], 2917: [0, 0, 0], 2918: [0, 0, 0], 2919: [0, 0, 0], 2920: [0, 0, 0], 2921: [0, 0, 0], 2922: [0, 0, 0], 2923: [0, 0, 0], 2924: [0, 0, 0], 2925: [0, 0, 0], 2926: [0, 0, 0], 2927: [0, 0, 0], 2928: [0, 0, 0], 2929: [0, 0, 0], 2930: [0, 0, 0], 2931: [0, 0], 2932: [0, 0, 0], 2933: [0, 0, 0], 2934: [0, 0, 0], 2935: [0, 0, 0], 2936: [0, 0, 0], 2937: [0, 0, 0], 2938: [0, 0, 0], 2939: [0, 0, 0], 2940: [0, 0, 0], 2941: [0, 0, 0], 2942: [0, 0, 0], 2943: [0, 0, 0], 2944: [0, 0, 0], 2945: [0, 0, 0], 2946: [0, 0, 0], 2947: [0, 0, 0], 2948: [0, 0, 0], 2949: [0, 0, 0], 2950: [0, 0, 0], 2951: [0, 0, 0], 2952: [0, 0]}

In [117]:
for key in ans:
    sumlya = sum(ans[key])
    sumlya = sumlya/len(ans[key])
    ans[key] = sumlya
print(ans)

{2441: 0.0, 2442: 0.0, 2443: 0.0, 2444: 0.0, 2445: 0.0, 2446: 0.0, 2447: 0.0, 2448: 0.0, 2449: 0.0, 2450: 0.0, 2451: 0.0, 2452: 0.0, 2453: 0.0, 2454: 0.0, 2455: 0.0, 2456: 0.0, 2457: 0.0, 2458: 0.0, 2459: 0.0, 2500: 0.0, 2501: 0.0, 2502: 0.0, 2503: 0.0, 2504: 0.0, 2505: 0.0, 2506: 0.0, 2507: 0.0, 2508: 0.0, 2509: 0.0, 2510: 0.0, 2511: 0.0, 2512: 0.0, 2513: 0.0, 2514: 0.0, 2515: 0.0, 2516: 0.0, 2517: 0.0, 2518: 0.0, 2519: 0.0, 2520: 0.0, 2521: 0.0, 2522: 0.0, 2523: 0.0, 2524: 0.0, 2525: 0.0, 2526: 0.0, 2527: 0.0, 2528: 0.0, 2529: 0.0, 2530: 0.0, 2531: 0.0, 2532: 0.0, 2533: 0.0, 2534: 0.0, 2535: 0.0, 2536: 0.0, 2537: 0.0, 2538: 0.0, 2539: 0.0, 2540: 0.0, 2541: 0.0, 2542: 0.0, 2543: 0.0, 2544: 0.0, 2545: 0.0, 2546: 0.0, 2547: 0.0, 2548: 0.0, 2549: 0.0, 2550: 0.0, 2551: 0.0, 2552: 0.0, 2553: 0.0, 2554: 0.0, 2555: 0.0, 2556: 0.0, 2557: 0.0, 2558: 0.0, 2559: 0.0, 2600: 0.0, 2601: 0.0, 2602: 0.0, 2603: 0.0, 2604: 0.0, 2605: 0.0, 2606: 0.0, 2607: 0.0, 2608: 0.0, 2609: 0.0, 2610: 0.0, 2611: 0.0, 2612: 0.0, 2613: 0.0, 2614: 0.0, 2615: 0.0, 2616: 0.0, 2617: 0.0, 2618: 0.0, 2619: 0.0, 2620: 0.0, 2621: 0.0, 2622: 0.0, 2623: 0.0, 2624: 0.0, 2625: 0.0, 2626: 0.0, 2627: 0.0, 2628: 0.0, 2629: 0.0, 2630: 0.0, 2631: 0.0, 2632: 0.0, 2633: 0.0, 2634: 0.0, 2635: 0.0, 2636: 0.0, 2637: 0.0, 2638: 0.0, 2639: 0.0, 2640: 0.0, 2641: 0.0, 2642: 0.0, 2643: 0.0, 2644: 0.0, 2645: 0.0, 2646: 0.0, 2647: 0.0, 2648: 0.0, 2649: 0.0, 2650: 0.0, 2651: 0.0, 2652: 0.0, 2653: 0.0, 2654: 0.0, 2655: 0.0, 2656: 0.0, 2657: 0.0, 2658: 0.0, 2659: 0.0, 2700: 0.0, 2701: 0.0, 2702: 0.0, 2703: 0.0, 2704: 0.0, 2705: 0.0, 2706: 0.0, 2707: 0.0, 2708: 0.0, 2709: 0.0, 2710: 0.0, 2711: 0.0, 2712: 0.0, 2713: 0.0, 2714: 0.0, 2715: 0.0, 2716: 0.0, 2717: 0.0, 2718: 0.0, 2719: 0.0, 2720: 0.0, 2721: 0.0, 2722: 0.0, 2723: 0.0, 2724: 0.0, 2725: 0.0, 2726: 0.0, 2727: 0.0, 2728: 0.0, 2729: 0.0, 2730: 0.0, 2731: 0.0, 2732: 0.0, 2733: 0.0, 2734: 0.0, 2735: 0.0, 2736: 0.0, 2737: 0.0, 2738: 0.0, 2739: 0.0, 2740: 0.0, 2741: 0.0, 2742: 0.0, 2743: 0.0, 2744: 0.0, 2745: 0.0, 2746: 0.0, 2747: 0.0, 2748: 0.0, 2749: 0.0, 2750: 0.0, 2751: 0.0, 2752: 0.0, 2753: 0.0, 2754: 0.0, 2755: 0.0, 2756: 0.0, 2757: 0.0, 2758: 0.0, 2759: 0.0, 2800: 0.0, 2801: 0.0, 2802: 0.0, 2803: 0.0, 2804: 0.0, 2805: 0.0, 2806: 0.0, 2807: 0.0, 2808: 0.0, 2809: 0.0, 2810: 0.0, 2811: 0.0, 2812: 0.0, 2813: 0.0, 2814: 0.0, 2815: 0.0, 2816: 0.0, 2817: 0.0, 2818: 0.0, 2819: 0.0, 2820: 0.0, 2821: 0.0, 2822: 0.0, 2823: 0.0, 2824: 0.0, 2825: 0.0, 2826: 0.0, 2827: 0.0, 2828: 0.0, 2829: 0.0, 2830: 0.0, 2831: 0.0, 2832: 0.0, 2833: 0.0, 2834: 0.0, 2835: 0.0, 2836: 0.0, 2837: 0.0, 2838: 0.0, 2839: 0.0, 2840: 0.0, 2841: 0.0, 2842: 0.0, 2843: 0.0, 2844: 0.0, 2845: 0.0, 2846: 0.0, 2847: 0.0, 2848: 0.0, 2849: 0.0, 2850: 0.0, 2851: 0.0, 2852: 0.0, 2853: 0.0, 2854: 0.0, 2855: 0.0, 2856: 0.0, 2857: 0.0, 2858: 0.0, 2859: 0.0, 2900: 0.0, 2901: 0.0, 2902: 0.0, 2903: 0.0, 2904: 0.0, 2905: 0.0, 2906: 0.0, 2907: 0.0, 2908: 0.0, 2909: 0.0, 2910: 0.0, 2911: 0.0, 2912: 0.0, 2913: 0.0, 2914: 0.0, 2915: 0.0, 2916: 0.0, 2917: 0.0, 2918: 0.0, 2919: 0.0, 2920: 0.0, 2921: 0.0, 2922: 0.0, 2923: 0.0, 2924: 0.0, 2925: 0.0, 2926: 0.0, 2927: 0.0, 2928: 0.0, 2929: 0.0, 2930: 0.0, 2931: 0.0, 2932: 0.0, 2933: 0.0, 2934: 0.0, 2935: 0.0, 2936: 0.0, 2937: 0.0, 2938: 0.0, 2939: 0.0, 2940: 0.0, 2941: 0.0, 2942: 0.0, 2943: 0.0, 2944: 0.0, 2945: 0.0, 2946: 0.0, 2947: 0.0, 2948: 0.0, 2949: 0.0, 2950: 0.0, 2951: 0.0, 2952: 0.0}

In [119]:
data_list = [(time, gearValue) for time, gearValue in ans.items()]
new_df = pd.DataFrame(data_list, columns=['time', 'data'])
new_df.head()
new_df.to_csv('file.csv')

   time  data
0  2441   0.0
1  2442   0.0
2  2443   0.0
3  2444   0.0
4  2445   0.0